language: objective-c
before_install:

    - gem install cocoapods --no-ri --no-rdoc
    - gem install xcpretty --no-ri --no-rdoc

    - pod --version
    #- xcpretty --version

script: make ci

notifications:
    email: false
